"""job_openings_and_applications_updated

Revision ID: 0dcb51477945
Revises: 71a1bb289d1d
Create Date: 2026-03-05 15:05:00.195722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dcb51477945'
down_revision: Union[str, Sequence[str], None] = '71a1bb289d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobopenings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='jobtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobapplications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('portfolio_link', sa.String(), nullable=True),
    sa.Column('jobOpening_id', sa.Uuid(), nullable=False),
    sa.Column('about_applicant', sa.String(), nullable=False),
    sa.Column('resume', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['jobOpening_id'], ['jobopenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobapplications')
    op.drop_table('jobopenings')
    # ### end Alembic commands ###
