"""description added in assignment

Revision ID: 1721d4d5074d
Revises: 8ba51a22da1b
Create Date: 2026-02-09 11:45:14.806781

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1721d4d5074d'
down_revision: Union[str, Sequence[str], None] = '8ba51a22da1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE assignment SET description = 'No description provided.' WHERE description IS NULL")
    op.alter_column('assignment', 'description', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'description')
    # ### end Alembic commands ###
