"""class name unique key changed

Revision ID: 2a672fc95695
Revises: f9e3f6119e3a
Create Date: 2026-06-09 12:22:57.871070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a672fc95695'
down_revision: Union[str, Sequence[str], None] = 'f9e3f6119e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('class_name_key'), 'class', type_='unique')
    op.drop_constraint(op.f('uq_teacher_class_year'), 'teacher_class_history', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_teacher_class_year'), 'teacher_class_history', ['teacher_id', 'class_id', 'academic_year_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('class_name_key'), 'class', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
