"""class level attendance and holidays

Revision ID: 5b06c4da4526
Revises: c3d4e5f6a7b8
Create Date: 2026-03-17 12:33:47.830534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '5b06c4da4526'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'holiday' not in inspector.get_table_names():
        op.create_table(
            'holiday',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('date', sa.DateTime(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('description', sa.String(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('date')
        )

    op.execute('TRUNCATE TABLE attendance CASCADE')
    op.add_column('attendance', sa.Column('class_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('attendance_lesson_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'class', ['class_id'], ['id'])
    op.drop_column('attendance', 'lesson_id')
    op.drop_constraint(op.f('fk_lesson_academic_year'), 'lesson', type_='foreignkey')
    op.create_foreign_key(None, 'lesson', 'academic_year', ['academic_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('holiday')

    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lesson_academic_year'), 'lesson', 'academic_year', ['academic_year_id'], ['id'],
                          ondelete='SET NULL')
    op.add_column('attendance', sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_lesson_id_fkey'), 'attendance', 'lesson', ['lesson_id'], ['id'])
    op.drop_column('attendance', 'class_id')
    # ### end Alembic commands ###
