"""alter photo gallery table with is_sport field.

Revision ID: 5f4f9c70dc77
Revises: 9b3b2e10c02b
Create Date: 2026-03-04 23:53:14.440812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4f9c70dc77'
down_revision: Union[str, Sequence[str], None] = '9b3b2e10c02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photogallery', sa.Column('is_sport', sa.Boolean()))
    op.execute("UPDATE photogallery SET is_sport = false")
    op.alter_column('photogallery', 'is_sport', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photogallery', 'is_sport')
    # ### end Alembic commands ###
