"""pdf_name col added in assignment

Revision ID: 7433104653ef
Revises: 061874bf645b
Create Date: 2025-12-17 10:31:32.707984

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7433104653ef'
down_revision: Union[str, Sequence[str], None] = '061874bf645b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('pdf_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE assignment SET pdf_name='xyz.pdf' WHERE pdf_name IS NULL")
    op.alter_column('assignment', 'pdf_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'pdf_name')
    # ### end Alembic commands ###
