"""Add dob column

Revision ID: 7af24aef8e1c
Revises: 
Create Date: 2025-12-02 13:07:34.956204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af24aef8e1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('announcement', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('event', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('student', sa.Column('dob', sa.Date(), nullable=True))
    op.execute("UPDATE student SET dob = '2000-01-01' WHERE dob IS NULL")
    op.alter_column('student', 'dob', nullable=False)

    op.add_column('teacher', sa.Column('dob', sa.Date(), nullable=True))
    op.execute("UPDATE teacher SET dob = '2000-01-01' WHERE dob IS NULL")
    op.alter_column('teacher', 'dob', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'dob')
    op.drop_column('student', 'dob')
    op.alter_column('event', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('announcement', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('admin', 'is_delete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
