"""student class history

Revision ID: ba9009090262
Revises: a1b2c3d4e5f6
Create Date: 2026-03-10 16:37:39.891352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba9009090262'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'img',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.JSON(),
                    existing_nullable=True)
    op.alter_column('photogallery', 'is_sport', server_default=None)

    # Ensure the studentstatus enum exists with the correct lowercase values.
    # The first migration attempt may have partially created it with uppercase values
    # ('ACTIVE', 'GRADUATED', 'INACTIVE') before rolling back the ALTER TABLE, leaving
    # a stale enum in the DB.  We detect and fix that here.
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT string_agg(e.enumlabel, ',' ORDER BY e.enumsortorder) "
        "FROM pg_type t JOIN pg_enum e ON e.enumtypid = t.oid "
        "WHERE t.typname = 'studentstatus'"
    ))
    current_labels = result.scalar()  # e.g. 'ACTIVE,GRADUATED,INACTIVE' or 'active,graduated,inactive' or None

    if current_labels is not None and current_labels != 'active,graduated,inactive':
        # Wrong values (uppercase) — convert column to plain text first, then drop
        conn.execute(sa.text("ALTER TABLE student ALTER COLUMN status TYPE TEXT USING status::text"))
        conn.execute(sa.text("DROP TYPE studentstatus"))
        current_labels = None  # will be recreated below

    if current_labels is None:
        conn.execute(sa.text("CREATE TYPE studentstatus AS ENUM ('active', 'graduated', 'inactive')"))

    # Now the enum has the correct lowercase values — cast the column
    conn.execute(sa.text(
        "ALTER TABLE student ALTER COLUMN status TYPE studentstatus USING status::studentstatus"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE student ALTER COLUMN status TYPE VARCHAR USING status::text")
    sa.Enum('active', 'graduated', 'inactive', name='studentstatus').drop(op.get_bind(), checkfirst=True)
    op.drop_column('photogallery', 'is_sport')
    op.alter_column('event', 'img',
                    existing_type=sa.JSON(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    # ### end Alembic commands ###
