"""banner table alter with active field

Revision ID: d1c864f1cce0
Revises: a9f4ed1f00fb
Create Date: 2026-03-01 14:08:47.053352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c864f1cce0'
down_revision: Union[str, Sequence[str], None] = 'a9f4ed1f00fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('is_active', sa.Boolean()))
    op.execute("UPDATE banner SET is_active = true")
    op.alter_column("banner", "is_active", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'is_active')
    # ### end Alembic commands ###
