"""is_delete added attendance

Revision ID: dc86806d688f
Revises: 7af24aef8e1c
Create Date: 2025-12-03 09:41:42.945769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc86806d688f'
down_revision: Union[str, Sequence[str], None] = '7af24aef8e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.execute("UPDATE attendance SET is_delete = FALSE WHERE is_delete is NULL")
    op.alter_column('attendance', 'is_delete', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'is_delete')
    # ### end Alembic commands ###
